### ISSUE TITLE
Strange error when playing

### ISSUE THREAD

**Issue by ddesmarest** [ddesmarest/so_music#28]
2016-06-15 13:27:12,644 - Player - ERROR - list index out of range : 
Traceback (most recent call last):
  File "/home/ddesmarest/work/so_music/src/player/FlacStreamAlsaPlayer.py", line 28, in stop
    decoder = self.**get_decoder_process**()
  File "/home/ddesmarest/work/so_music/src/player/AlsaBasePlayer.py", line 29, in **get_decoder_process**
    return psutil.Process(self.process.pid).get_children(True)[-1]
IndexError: list index out of range

127.0.0.1 - - [15/Jun/2016 13:27:12] "GET /play_album/qobuz/5051

**Comment by ddesmarest** [comment]
See also :    state = FLAC__STREAM_DECODER_READ_FRAME
2016-09-22 13:56:54,268 - Player - ERROR - In thread : exit read loop
2016-09-22 13:56:54,269 - Player - DEBUG - THREAD END....
127.0.0.1 - - [22/Sep/2016 13:56:54] "GET /player_status HTTP/1.1" 200 426

**Comment by ddesmarest** [comment]
Fixed by pull request #29
